site:
  title:  Java Architecture and Core Concepts
  start_page: java_arhcitecture::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
